version: "3"
services:
  db:
    image: mysql:5.7
    volumes:
      - "./data/mysql:/var/lib/mysql"
      - "./conf/mysql/my.cnf:/etc/my.cnf"
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pass
    ports:
      - "3306:3306"

  redis:
    image: redis:5
    volumes:
      - "./data/redis:/data"
    container_name: redis
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
